CREATE DATABASE [义耱0] ON PRIMARY 
( NAME = N'义耱0', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\义耱0.mdf' , SIZE = 49152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'义耱0_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\义耱0_log.ldf' , SIZE = 353216KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
ALTER DATABASE [义耱0] SET  DISABLE_BROKER
